rabbitmq:
  addresses: 192.168.94.128:5672
  username: admin
  password: 123456
  publisherConfirms: true
  demo:
    queue: demo3
    prefetch: 1
    concurrency: 2

mybatis:
  mapperLocations: classpath:mappers/*.xml

spring:
  datasource:
    name: test
    url: jdbc:mysql://192.168.94.128:3306/demo?useUnicode=true&characterEncoding=UTF-8&useTimezone=true&serverTimezone=GMT
    username: dudream
    password: 123456
    type: org.apache.commons.dbcp.BasicDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
